### ISSUE TITLE
Email notification after signup

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#10]
It is a good idea to send a welcome email notification to the new users after they signup on to the app. Keep the email template simple for now.

Sending email functionality is already there in the code; see how we send an invitation email to the users.

**Comment by Saptarshee94** [comment]
Issue addressed on PR #44 . Sample email screenshot:
![image](https://user-images.githubusercontent.com/45600689/195912306-2a4eff47-808a-400f-9702-8c61d916868b.png)
