### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by deepakprabhakara** [boxyhq/saas-starter-kit#1011]
Dark mode is broken in various places, we need to fix it.

**Comment by saqibtanveer786** [comment]
its amaze me that there is no live version of this kit

**Comment by deepakprabhakara** [comment]
@saqibtanveer786 There are plenty including our own SaaS, just not dark mode. :)

**Comment by saqibtanveer786** [comment]
@deepakprabhakara I want to work on this but what if it took some time.

**Comment by Musyonchez** [comment]
@deepakprabhakara was the darkmode issue completly fixed?

**Comment by deepakprabhakara** [comment]
Fixed in https://github.com/boxyhq/saas-starter-kit/pull/1042
