### ISSUE TITLE
Billing & subscriptions

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#12]

**Comment by dgwyer** [comment]
What payment gateway(s) were you thinking of supporting?

I know a popular one is Stripe but where I live (UK) I need a merchant of record vendor such as Gumroad, Lemon Squeezy, Paddle etc. Would be great if you also included an example of one of those (pref. Lemon Squeezy).

**Comment by twinkle77** [comment]
<img width="471" alt="image" src="https://github.com/boxyhq/saas-starter-kit/assets/17792166/aea48124-41b5-43d1-ba5d-a9cff7709a34">

I hope to arrive earlier. thx~

**Comment by pankaj9296** [comment]
when are billing and subscriptions coming?

**Comment by KazeroG** [comment]
@deepakprabhakara ReadMe need to be updated with the documentation 

![image](https://github.com/boxyhq/saas-starter-kit/assets/17680194/0dab4dd4-7e5c-4bcf-a8b9-8c00ecd17a26)
