### ISSUE TITLE
Add "npm run format" to pre-commit hooks

### ISSUE THREAD

**Issue by Musyonchez** [boxyhq/saas-starter-kit#1322]
I propose the integration of "npm run format" as a pre-commit hook. This approach not only streamlines the development process by consolidating commands but also ensures that new contributors, particularly those submitting pull requests for the first time, adhere to our formatting standards. This practice enhances code consistency and quality across the project.

**Comment by deepakprabhakara** [comment]
Thanks for the suggestion @Musyonchez. We used to have that but it became a hassle. It is now part of CI/CD so doesn't need to be complicated any further as a pre-commit hook. We don't merge PRs until all checks pass.
