### ISSUE TITLE
How to enable logging or instrumentation?

### ISSUE THREAD

**Issue by nopmop** [boxyhq/saas-starter-kit#1639]
Hi, I'm addding support for MongoDB but I get a browser notification saying: 
``` 
Invalid `prisma.user.create()` invocation:
Prisma needs to perform transactions, which requires your MongoDB server to be run as a replica set. https://pris.ly/d/mongodb-replica-set
```
while my terminal only shows the error `POST /api/auth/join 500` and that's it.
How do I enable logging / instrumentation to understand what's going on? 

Edit: please, besides changing `log: ["error"]` in `lib/prisma.ts`

**Comment by deepakprabhakara** [comment]
Hi @nopmop, unfortunately there is nothing more than the logging and tooling prisma provides in this case. We can't do much when the database is down.
