### ISSUE TITLE
npm package vulnerability 

### ISSUE THREAD

**Issue by Andrewx24** [boxyhq/saas-starter-kit#1730]
When I ran npm install on the project. 2 high securitity vulnerabilities where found in the packages by npm.This what npm reported in the terminal 

 saas-starter-kit % npm audit 
# npm audit report

next  14.0.0 - 14.2.9
Severity: high
Next.js Cache Poisoning - https://github.com/advisories/GHSA-gp8f-8m3g-qvj9
fix available via `npm audit fix --force`
Will install react-email@1.10.1, which is a breaking change
node_modules/react-email/node_modules/next
  react-email  1.10.1-canary.0 - 1.10.1-canary.18 || >=1.10.2-canary.0
  Depends on vulnerable versions of next
  node_modules/react-email

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

**Comment by niwsa** [comment]
@Andrewx24  Thanks for reporting this, we’ll investigate the issue and get back to you
