### ISSUE TITLE
Google - Github Callbacks

### ISSUE THREAD

**Issue by kubeworkz** [boxyhq/saas-starter-kit#181]
I was just setting up Github and Google SSO and I need to know what the format of the callback url is for Saas starter kit. Both Github and Google require it. Cheers, Dave

**Comment by devkiran** [comment]
The callback URL are

Github: `http://localhost:4002/api/auth/callback/github`
Google: `http://localhost:4002/api/auth/callback/google`

**Comment by kubeworkz** [comment]
Perfect, thanks
