### ISSUE TITLE
Directions on adding SSO connection with OIDC

### ISSUE THREAD

**Issue by abhiavadhani-zelar** [boxyhq/saas-starter-kit#1867]
Hi there,

I am using the starter kit and let me firstly appreciate how awesome this project is!

My issue is when setting up SSO connection with OIDC: even after adding the respective client credentials and OpenID discovery path, there isn't any SSO button on the login screen.

I wanted to know if there are any explicit instructions for the same as I saw instructions/videos only with respect to the SAML-SSO connection.

**Comment by niwsa** [comment]
@abhiavadhani-zelar You have to enable the saml auth provider [here](https://github.com/boxyhq/saas-starter-kit/blob/main/.env.example#L56) .

**Comment by abhiavadhani-zelar** [comment]
Well, that added the button on the login screen.
Thanks @niwsa , it worked!
Although, can we find these instructions somewhere for essential features like SSO, Directory Sync, etc.?
