### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by allanice001** [boxyhq/saas-starter-kit#187]
Default clone (main branch)
```
yarn install
yarn dev
```
Result:
```
Error: Cannot find module 'autoprefixer'
```
Okay, lets add the dependency:
```
yarn add -D autoprefixer
yarn dev
```
Next Error::
```
Error: Cannot find module 'daisyui'
```

Okay, lets fix this. I believe this is a direct dependency, so add it:
```
yarn add daisyui
yarn dev
```

Working at last

**Comment by allanice001** [comment]
https://github.com/boxyhq/saas-starter-kit/pull/188

**Comment by NathanTarbert** [comment]
Nice, I scanned `daisyui` with snyk advisor and it's clean. 

<img width="1419" alt="image" src="https://github.com/boxyhq/saas-starter-kit/assets/66887028/e5132558-b7f4-44b3-84cc-8a45aa801c34">
