### ISSUE TITLE
Delete SAML connection for a team

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#199]
- Add an option to delete the existing SAML connection.
- Only ADMIN or OWNER can delete the connection.
- Call Jackson delete method to delete the connection.

**Comment by niwsa** [comment]
The delete connection is now implemented as part of the SDK component. Role-based access needs to be looked into.

**Comment by niwsa** [comment]
Closing this as it's completed as part of UI SDK integration.
