### ISSUE TITLE
Close account

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#25]
TBD

**Comment by emmacode** [comment]
@devkiran please can you provide more details on this? Close account (Delete account) right?

**Comment by dasveloper** [comment]
> @devkiran please can you provide more details on this? Close account (Delete account) right?

Assuming this is about account/team deletion, could we also be sure to account for blockers cleanups. I.e. User can’t delete account without deleting or transferring teams they own. User can’t delete team without canceling subscriptions (once those are implemented). Or being sure to cancel them in post deleting webhook. Etc.

**Comment by yacineahmaich** [comment]
If you want me to start the implementation By adding account deletion  _(User can’t delete account without deleting or transferring teams they own)_  assign me this issue. I will be happy to work on it.
