### ISSUE TITLE
Create a 'Deploy to Heroku' Button

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#32]
The ‘Deploy to Heroku’ button enables users to deploy apps to Heroku without leaving the web browser, and with little or no configuration. The button is ideal for customers with a quick and easy way to deploy and configure a Heroku app.

**Comment by Saptarshee94** [comment]
Interest to contribute.

**Comment by devkiran** [comment]
@Saptarshee94 Sounds great. I'll assign the task to you.

**Comment by meenaljain0303** [comment]
I would like to contribute to this issue if its still available

**Comment by Saptarshee94** [comment]
Issue resolved in #35 . Review is required.

**Comment by devkiran** [comment]
Thanks, I'll do it shortly.

**Comment by devkiran** [comment]
Closed via #35
