### ISSUE TITLE
Update a member's role

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#33]
- Add an Edit button against a member in the "Team Members" section.
- Display a modal popup to choose a new role from Admin, Owner, or Member.
- Only Admin or Owner can edit a member's role.

**Comment by meenaljain0303** [comment]
I would like to work on this issue, if it's till open

**Comment by nalin-programmer** [comment]
I would like to work on this issue.

**Comment by devkiran** [comment]
Feel free to work on it. I've added more details into the issue description.
