### ISSUE TITLE
Add Dark mode

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#39]
The user should be able to choose their preference from the settings. 

Here is the basic idea. 

![dark-mode](https://user-images.githubusercontent.com/4593041/194928831-8a56bfc2-255b-4459-a215-668984be75be.png)

This UI is not implemented yet.

**Comment by gaurav-iitb** [comment]
please assign this to me I can do it quickly and I would love to work on it

**Comment by devkiran** [comment]
Sure. Let us know if you have any questions. Note: TailwindCSS for UI.

**Comment by devkiran** [comment]
@gaurav-iitb Let me know if you need any help with the task.

**Comment by ishaanbedi** [comment]
Hey, if this is up for a re-assignment, I'd love to work on it!

**Comment by kkumar-gcc** [comment]
@devkiran i would like to work on it.

**Comment by kkumar-gcc** [comment]
@devkiran I would like to work on this issue.

**Comment by devkiran** [comment]
Thanks for your interest. Let me collect the requirements for this feature and get back to you.

**Comment by kkumar-gcc** [comment]
> Thanks for your interest. Let me collect the requirements for this feature and get back to you.

Okay

**Comment by Rahul-Palamarthi** [comment]
I can contribute with the theme can you assign it to me

**Comment by Rahul-Palamarthi** [comment]
@devkiran can I upgrade the project with the shadcn-ui for the darkmode and various other components

**Comment by devkiran** [comment]
No, you can't use shadcn-ui for this project at the moment. We might consider it in the future, but not right now.

**Comment by devkiran** [comment]
@yacineahmaich assigning to you.
