### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#4]
As a user I want to reset my password when I forgot it.

**What needs to be done**
Build a new "forgot password" view where a user can enter his email address and request a new password. An email should send to the user with the password reset link.

**Comment by kkumar-gcc** [comment]
@devkiran please assign this issue to me. I want to work on it.

**Comment by devkiran** [comment]
@kkumar-gcc Great! I have assigned this issue to you. Please let me know if you have any questions.

**Comment by kkumar-gcc** [comment]
I have followed installation process mentioned in [Contributing Guide](https://github.com/boxyhq/saas-starter-kit/blob/main/CONTRIBUTING.md). But when i run `npm run dev` i am getting following errors.
```bash
npm run dev 


> next-saas@0.1.0 dev
> next dev --port 4002

ready - started server on 0.0.0.0:4002, url: http://localhost:4002
info  - Loaded env from /home/krish/saas-starter-kit/.env
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - automatically enabled Fast Refresh for 1 custom loader
info  - Using external babel configuration from /home/krish/saas-starter-kit/.babelrc
error - ./node_modules/next-i18next/dist/esm/appWithTranslation.js:8:0
Module not found: Can't resolve 'react-i18next'

Import trace for requested module:
./node_modules/next-i18next/dist/esm/index.js
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found

```
![image](https://user-images.githubusercontent.com/84431594/236477280-bfc6e951-75c9-440b-bab3-785f602c2106.png)

**Comment by devkiran** [comment]
@kkumar-gcc Can you pull the latest changes from the branch `main` and try again? I think this should be fixed now.
