### ISSUE TITLE
Configure Playwright to work with Next.js

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#40]

**Comment by Saptarshee94** [comment]
I would like to contribute to this issue.

**Comment by devkiran** [comment]
Great, I'll assign the task to you.

**Comment by Saptarshee94** [comment]
A question, is this issue only covers integrating playwright? I can test it by writing a sigle test to verify if integration is working.

**Comment by devkiran** [comment]
Yes, you are right. We'll add remaining tests later.

**Comment by Saptarshee94** [comment]
Issue addressed in PR #41
