### ISSUE TITLE
Rebuild the email templates using react.email for better consistency

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#418]
[React.email](https://react.email/) is a collection of high-quality, unstyled components for creating beautiful emails using React and TypeScript.

**Comment by Young-Einstein10** [comment]
Hello @devkiran, I'd love to work on this. 
Are there any specific designs in mind for the email templates, or should I just convert the current implementation to React.email?

**Comment by devkiran** [comment]
Thanks for your interest. We don't have any specific designs in mind. You can convert the current implementation to React.email.

We would like to keep it simple - A header with logo, body and simple footer with the company name and address.

Example https://demo.react.email/preview/dropbox-reset-password

Please open a draft PR with one of the email templates and we can review it.

**Comment by Young-Einstein10** [comment]
Alright, that sounds good.
