### ISSUE TITLE
Review the Svix webhook implementation and add missing webhook events

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#419]

**Comment by shartrooper** [comment]
@devkiran May I have the value that should be  added in  SVIX_API_KEY ? Webhooks tab is throwing bad request because I lack an apiKey

**Comment by devkiran** [comment]
You can create one from svix.com 
https://docs.svix.com/api-keys

**Comment by shartrooper** [comment]
I've been checking out all the webhook event types available to create: member.created, member.deleted, invitation.created, invitation.deleted. If you add then in your own dashboard those work , which webhooks are missing?
![image](https://github.com/boxyhq/saas-starter-kit/assets/21326996/9afaf377-7543-4fb6-baf1-991cb2972116)

**Comment by devkiran** [comment]
Thanks for reviewing. Let me check and get back to you.

**Comment by devkiran** [comment]
We're good to go with the current set of webhooks. We'll add more when we need them.
