### ISSUE TITLE
Ask for confirmation before deleting a resource

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#447]
The user should be asked for confirmation before deleting a team member and webhook. We already have a confirmation modal component that can be used for this.

**Comment by emmacode** [comment]
@NathanTarbert @devkiran I'd like to work on this. Please assign this to me

**Comment by NathanTarbert** [comment]
Hi @emmacode, you have been assigned. Thanks so much!

**Comment by devkiran** [comment]
Hi @emmacode, I see you have been assigned to this issue and noticed @yacineahmaich has created a PR for the same issue. Maybe you can check some other issues to work on? Thanks!

**Comment by emmacode** [comment]
Alright! Will work on another issue @devkiran
