### ISSUE TITLE
Include a theme toggler in the navbar

### ISSUE THREAD

**Issue by Young-Einstein10** [boxyhq/saas-starter-kit#461]
Having to log in and navigate to the user settings page is a long journey to change the theme. There should be a theme toggler in the Navbar (Public and Private) to make this accessible to everyone.

Example
![Screenshot 2023-09-06 at 08 26 34](https://github.com/boxyhq/saas-starter-kit/assets/45533201/6ab59f0e-456f-469c-9f01-4985db733fee)

I'd love to work on this.

**Comment by devkiran** [comment]
Nice idea. You can work on it. Please try to reuse the existing logic from the account setting page.
