### ISSUE TITLE
Add profile picture upload field on account page

### ISSUE THREAD

**Issue by niwsa** [boxyhq/saas-starter-kit#49]
Design and implement the UI components necessary to add a profile picture upload field on the Account Page.

- This task focuses solely on the user interface (UI) and does not involve backend functionality.
- Display the avatar image on the Account Page.
- Clicking on the avatar image should open image upload dialog.

<img width="229" alt="Screenshot 2022-10-17 at 4 23 25 PM" src="https://user-images.githubusercontent.com/3107922/196159802-97948b2f-77fc-4a01-ab90-260c311c61e7.png">

**Comment by omen1650ti** [comment]
interested to contribute to this issue.

**Comment by peterraju** [comment]
Iam intrested to contribute in this issue

**Comment by niwsa** [comment]
@omen1650ti Assigning this issue to you. Let me know if you have any further questions.

**Comment by kkumar-gcc** [comment]
@devkiran i want to work on this issue.

**Comment by devkiran** [comment]
Ok, thanks for the interest. If you have any questions, please feel free to ask here or on Discord.
