### ISSUE TITLE
[e2e test] Login to the SaaS starter kit UI

### ISSUE THREAD

**Issue by niwsa** [boxyhq/saas-starter-kit#51]
While running the e2e test, a user can be created on the fly and used to login to the dashboard.

**Comment by peterraju** [comment]
I like to solve this issue

**Comment by niwsa** [comment]
@peterraju  Sure. Assigning this issue to you. Let me know in case you need any help

**Comment by asi309** [comment]
Is this open? I would like to solve this issue

**Comment by emmacode** [comment]
@NathanTarbert please assign this to me
