### ISSUE TITLE
Authenticated user shouldn't be able to access landing page

### ISSUE THREAD

**Issue by shartrooper** [boxyhq/saas-starter-kit#535]
An user after login can still redirect to the landing page and, hence, to the sign in and sign up pages. IMO, authenticated users ought to be redirected towards the dashboard if they attempt to access through the root URL '/'. 

With React Router, this can be achieved by dynamically mounting either "private" route components if there's an active session (token authentication or some other means), or "public" route components if there is not. On Next Im not pretty sure yet how's implemented, but I can learn and perform this task if you people agreed in limiting route access by ongoing session.

**Comment by asi309** [comment]
Is this open? I would like to work on this

**Comment by shartrooper** [comment]
> Is this open? I would like to work on this

Sure, @ me when you open the PR. @deepakprabhakara can you assign this issue to @asi309 ?

**Comment by NathanTarbert** [comment]
Thank @shartrooper for working on this issue!
Let us know if you have any questions.

**Comment by devkiran** [comment]
I think it is okay to have the landing page accessible to authenticated users. Sometime they might have to access the pricing or other information after they have logged in. We already do redirect if they try to access login/signup page.
