### ISSUE TITLE
Implement a minimum length for passwords

### ISSUE THREAD

**Issue by deepakprabhakara** [boxyhq/saas-starter-kit#546]

**Comment by deepakprabhakara** [comment]
https://pages.nist.gov/800-63-3/sp800-63-3.html recommends a minimum length of 8

**Comment by Dhoni77** [comment]
Hi @deepakprabhakara  can you assign this issue to me

**Comment by deepakprabhakara** [comment]
@Dhoni77 Apologies, we already have a PR created by @rohitmondal03 here - https://github.com/boxyhq/saas-starter-kit/pull/557
