### ISSUE TITLE
Add a "show password" icon to the Login and Signup pages 

### ISSUE THREAD

**Issue by deepakprabhakara** [boxyhq/saas-starter-kit#558]
NIST Password guidelines suggest making the UX easier for users to avoid mistyping their passwords. An eye icon to toggle the content in the password field feels like a nice feature to have.

**Comment by abdulbari149** [comment]
Hey I would like to work on it

**Comment by vivekBoii** [comment]
done it already please check my PR sir

**Comment by devkiran** [comment]
@vivekBoii I see you've closed your PR https://github.com/boxyhq/saas-starter-kit/pull/568

**Comment by jatingodnani** [comment]
@devkiran  @deepakprabhakara  when i am pushing my code in my local repo it showing this
![Screenshot 2023-10-11 130239](https://github.com/boxyhq/saas-starter-kit/assets/97869761/3972774c-11d3-4734-90fa-403fd52c0a46)

**Comment by deepakprabhakara** [comment]
@jatingodnani You have to fork our repo and submit a PR from there.

**Comment by jatingodnani** [comment]
![Screenshot 2023-10-11 132244](https://github.com/boxyhq/saas-starter-kit/assets/97869761/ad73cfa1-0a4e-4238-a413-258bc5b4d39b)
@deepakprabhakara already forked
