### ISSUE TITLE
Improve Error Handling for New Member Invitations

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#563]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023). 

___

### Current Behavior:
Currently, when a user attempts to invite a new member by entering their email address, and that email address is invalid or doesn't meet the expected format, the app doesn't provide an error. It simply keeps the user on the same page, which can be confusing.

### Expected Behavior:
We should enhance this feature to provide more user-friendly error handling. When a user enters an invalid email address, the app should display a clear error message letting the user know there is an issue. This way, users will understand what went wrong and how to correct it.

### Impact:
This enhancement will significantly improve the user experience, especially for those who might make minor mistakes when entering email addresses. It aligns with our goal of making the app more user-friendly and efficient.

**Comment by Kiran-Alex** [comment]
Please Assign this issue to me I would Like to contribute to this Issue

**Comment by ArslanYM** [comment]
Can I work on this?

**Comment by jatingodnani** [comment]
@NathanTarbert i am not able to login.it showing error
