### ISSUE TITLE
User agrees to Terms & Conditions during Signup

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#564]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023). 

___

### User Story:
As a user is signing up, they should have to agree to the Terms and Conditions (T&Cs) before completing the signup process.

### Acceptance Criteria:
- A checkbox labeled "I agree to the Terms and Conditions" should be added to the signup page.
- The checkbox must be unchecked by default.
- Users should not be able to submit the signup form unless they check the "I agree to the Terms and Conditions" checkbox.

### Additional Information:
This feature is essential for ensuring that all users acknowledge and agree to the Terms and Conditions of the application. It adds a layer of legal protection and compliance to our signup process.

**Comment by olamide203** [comment]
Hi there👋, I would like to work on this.

**Comment by ShubhamSingh-S34** [comment]
Hi there I would like you to assign this issue to me

**Comment by ShubhamSingh-S34** [comment]
@NathanTarbert  I have made a pull request and solved the issues #574

**Comment by olamide203** [comment]
> @NathanTarbert I have made a pull request and solved the issues #574

Hi @ShubhamSingh-S34 please ensure you are assigned an issue before working on it next time. and avoid working on an issue that has been assignd to someone else to make the work of the maintainers easier.
