### ISSUE TITLE
Add Proper Meta Titles for All Pages

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#565]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

### User Story:
As a user, I want each page of the application to have a meaningful and informative meta title displayed on the browser tab for easier navigation and understanding of the page's content.

### Acceptance Criteria:
- Each page of the application should have a unique and descriptive meta title.
- Meta titles should accurately represent the content and purpose of each page.
- The meta titles should be concise and clear, providing users with a quick understanding of what each page is about.
- Changes to meta titles should not negatively impact the application's performance.

**Comment by AniruddhaGawali** [comment]
I can help in this can you assign it to me

**Comment by AniruddhaGawali** [comment]
hey can you tell me which pages need to add these meta tags

> I can help in this can you assign it to me

**Comment by ShrutiKolla** [comment]
@NathanTarbert Can you assign this task to me?

**Comment by devkiran** [comment]
@AniruddhaGawali Please check all the pages. Let me know if you're working on it.

**Comment by AniruddhaGawali** [comment]
> @AniruddhaGawali Please check all the pages. Let me know if you're working on it.

Yes I will complete it today

**Comment by 0xJamin** [comment]
Hi @NathanTarbert, what are the pages that need this meta titles, could you provide a list of them?

Thank you
