### ISSUE TITLE
Add Terms and Conditions Page

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#566]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

### User Story:
As a user, I want a dedicated "Terms and Conditions" (T&C) page on the application. The T&C page should include a styled H2 title with a **#25c2a0** border box around the body for improved readability and presentation. 

### Acceptance Criteria:
- Create a new page titled "Terms and Conditions" accessible from the application's navigation menu.
- On the "Terms and Conditions" page, include an H2 title that clearly indicates "Terms and Conditions."
- Apply a visually appealing **#25c2a0** border box around the body of the T&C content to enhance its readability and presentation.
- Test the page to ensure it displays correctly on various devices and browsers.

**Comment by DarkSoul26** [comment]
I would like to take a look into this, please assign it to me @NathanTarbert .

**Comment by vivekBoii** [comment]
If content Provided then I can work on this Issue for Sure Or I should use Lorem text

**Comment by Akshatverma01** [comment]
I have a good experience of making such web-pages. I would like to do it and ensure you that your conditions will fulfill with a responsive design.

**Comment by DarkSoul26** [comment]
You guys can start working on it, I don't have the terms and conditions that needs to be added.

**Comment by NathanTarbert** [comment]
@Akshatverma01, are you working on this issue?

**Comment by Akshatverma01** [comment]
Yes. Will pr soon. Do I need to add content in the page? Or only layout?

**Comment by devkiran** [comment]
@Akshatverma01 Closing this issue, no longer relevant. We can set `NEXT_PUBLIC_TERMS_AND_CONDITIONS_URL` with a URL to the terms and conditions page.
