### ISSUE TITLE
Fix Responsive Issues

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#567]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

### User Story:
As a user, I expect the application to be responsive and display correctly on various devices and screen sizes. Currently, there may be some responsive issues that need attention and fixing.

### Acceptance Criteria:
- Perform a comprehensive review of the application on different devices (desktop, tablet, mobile sizes).
- Identify and document any responsive issues that are affecting the user experience.
- Prioritize and address each responsive issue systematically.
- Test the fixes on various devices and browsers to ensure they resolve the problems effectively.
- Once all responsive issues are resolved, verify that the application looks and functions correctly on different screen sizes.

### Additional Information:
Ensuring that the application is responsive is essential for providing a seamless user experience. Fixing responsive issues will enhance usability and accessibility for all users, regardless of their device.

**Comment by AniruddhaGawali** [comment]
i can help in that can you assign it to me

**Comment by NathanTarbert** [comment]
@AniruddhaGawali, we need all client side pages to be responsive
