### ISSUE TITLE
"Create an account" not clearly visible in dark mode

### ISSUE THREAD

**Issue by rohitmondal03** [boxyhq/saas-starter-kit#576]
### Description
While in dark mode, in `auth/join` route, the heading **Create an account** i.e. heading is not clearly visible

### Steps to reproduce
Install a local copy in your machine, then run command `npm run dev` and then head to URL `http://localhost:4002/auth/join`.
![Screenshot (94)](https://github.com/boxyhq/saas-starter-kit/assets/107113353/51b46c1f-6a57-43ab-8d85-e7a2a599b00d)

**Comment by vivekBoii** [comment]
please label it with hactoberfest

**Comment by DevanshKyada27** [comment]
hey @devkiran can you please assign this problem to me

want to contribute and want to solve this issue

**Comment by devkiran** [comment]
@DevanshKyada27 There is a PR opened for this issue. Can you please look into other issues?
'?
