### ISSUE TITLE
Improve Webhook Creation Process

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#588]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

**Description:**
Currently, the webhook creation process allows users to create a webhook without selecting any event. This can lead to unnecessary webhooks that aren't associated with any specific event, causing confusion and clutter.

**Expected Behavior:**
To enhance clarity and usability, users should be required to choose at least one event when creating a webhook. This ensures that each webhook serves a specific purpose and is associated with relevant events.

**Proposed Solution:**
- Modify the webhook creation interface to make event selection a mandatory step. Users should not be able to proceed with webhook creation until they've chosen at least one event.

**Additional Information:**
This change will streamline webhook management, improve organization, and prevent the creation of redundant or unused webhooks.

**Comment by ShatilKhan** [comment]
Please assign me this issue & maybe share some steps for which files to changws

**Comment by devkiran** [comment]
@ShatilKhan Signup and look at the Webhook tab under a team. You'll see the Webhook management form there.
