### ISSUE TITLE
Enhance Domain Input Validation in Team Settings

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#589]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

**Description:**
In the Team Settings, the domain input field currently accepts any string as input, which can lead to inaccuracies and inconsistencies. To improve data integrity and user experience, we should implement domain name validation both in the frontend and backend.

**Expected Behavior:**
When users enter a domain in the **Team Settings**, the system should verify that it's a valid domain name format. This validation should occur in real-time on the frontend to provide immediate feedback and should also be enforced on the backend to ensure data consistency.

**Proposed Solution:**
- Implement frontend validation that checks domain name format as users type.
- Enforce backend validation to reject invalid domain names when saving settings.
- Provide clear error messages for users attempting to enter an invalid domain name.

**Additional Information:**
Implementing this validation will ensure that domain names entered in Team Settings are accurate and valid, reducing potential errors and ensuring data consistency across the platform.

**Comment by jatingodnani** [comment]
Interested @NathanTarbert 
Can you assign me this issue

**Comment by Mohitraut07** [comment]
I would like to solve the issue can you assign it to me.

**Comment by Bitnagar** [comment]
@Mohitraut07 In this repo, we can make a PR without getting the issue assigned.
