### ISSUE TITLE
Implement Minimum Password Length Check on Update Password Page

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#590]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

**Description:**
Currently, the password update page (/settings/password) allows users to set passwords of any length. To enhance security and ensure strong password practices, we should add a minimum password length check on both the client and server sides.

**Expected Behavior:**
[NIST](https://pages.nist.gov/800-63-3/sp800-63-3.html) recommends a password length of at least 8.
When users attempt to update their password on the **/settings/password** page, the system should validate that the new password meets the minimum length requirement. This validation should occur in real time on the client side for immediate feedback and on the server side to enforce security standards.

**Proposed Solution:**
- Implement client-side validation that checks the minimum password length as users type.
- Enforce server-side validation to reject password updates that don't meet the minimum length requirement.
- Provide clear error messages for users attempting to set a password that's too short.

**Additional Information:**
Implementing this validation will enhance the security of user accounts by ensuring that passwords meet a minimum length requirement, a common best practice in password management.

**Comment by jatingodnani** [comment]
Interested @NathanTarbert 
Can you assign me this issue

**Comment by jatingodnani** [comment]
![Screenshot 2023-10-08 100136](https://github.com/boxyhq/saas-starter-kit/assets/97869761/2128e75f-d2a1-47bf-9e87-39eb456fddc6)
authentication showing error

**Comment by jatingodnani** [comment]
@NathanTarbert can you assigned me this issue and tell how to pass login check in local
