### ISSUE TITLE
[Docs] Simplify CONTRIBUTING.md

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [boxyhq/saas-starter-kit#593]
Hey, I'd like to make the setup instruction in the CONTRIBUTING.md file simpler. The current steps are a bit unclear because they mention either one option without specifying. Also, it's a good idea to replace "boxyhq" with "your_github_name" because contributors get their username after they fork the repo. This change will make it less confusing, especially for beginners. Here's how I want to change the setup instructions:

1. Set Up

   - First, fork the repository.
   - Next, clone the repository by using this command:
     ```
     git clone https://github.com/<your_github_username>/saas-starter-kit.git
     ```

**Comment by NathanTarbert** [comment]
Hi @Shiva-Sai-ssb, feel free to submit a PR so we can review your change.

**Comment by Shiva-Sai-ssb** [comment]
> Hi @Shiva-Sai-ssb, feel free to submit a PR so we can review your change.

Thank you. I will submit the Pull request ASAP.
