### ISSUE TITLE
i18n: Identify Untranslated Text and Include it in locales/en/common.json

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#600]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

**Objective:** Enhance internationalization (i18n) by identifying text that requires translation and adding it to the locales/en/common.json file.

## Details:
As we strive to make our application accessible to a global audience, it's crucial to ensure that all text elements are properly translated. This includes not only the user-facing content but also any strings used for system messages, prompts, or labels.

## Action Items:
Review the entire frontend codebase to identify any text that has not yet been included in the translation file.

Once identified, add these text strings to the locales/en/common.json file, ensuring they are appropriately categorized and documented for translators.

Test the application to verify that all newly added text strings display correctly in English.

**Comment by Dhoni77** [comment]
I'm interested to work on this

**Comment by devkiran** [comment]
Feel free to submit a PR so we can review your change.

**Comment by belkhoujaons** [comment]
I created a PR for this issue, please review it and link it to this issue before merging , thanks !

**Comment by belkhoujaons** [comment]
can I submit another PR as an enhancement ? ( adding translation for another module )
