### ISSUE TITLE
Star the SaaS Starter Kit Repository! 🚀

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#616]
We support open-source & Hacktoberfest!  

A ⭐ star shows your support and we greatly appreciate it.

**Comment by jatingodnani** [comment]
Done @NathanTarbert

**Comment by NathanTarbert** [comment]
Thank you @jatingodnani!!

**Comment by jatingodnani** [comment]
@NathanTarbert add more issue

**Comment by NathanTarbert** [comment]
@jatingodnani, I will add more issues today!

**Comment by asg5704** [comment]
I just started on my journey to create a SaaS and this is very informational especially around NextAuth. Thank you!

**Comment by noobmaster19** [comment]
Hey team, this is wonderful, thank you for this!

**Comment by devkiran** [comment]
@noobmaster19 Thank you.

**Comment by shartrooper** [comment]
starred

**Comment by diogomoreira** [comment]
Done!

**Comment by NathanTarbert** [comment]
Thank you @shartrooper!  ❤️

**Comment by NathanTarbert** [comment]
Thank you so much @diogomoreira ❤️

**Comment by NathanTarbert** [comment]
That's great to hear @noobmaster19, thanks for the amazing feedback! ❤️

**Comment by NathanTarbert** [comment]
This is awesome to hear @asg5704 ❤️
