### ISSUE TITLE
Sign in button not visible

### ISSUE THREAD

**Issue by rohitmondal03** [boxyhq/saas-starter-kit#619]
"Sign in" button present in home page `localhost:4002` in not visible in dark mode.
![Screenshot (96)](https://github.com/boxyhq/saas-starter-kit/assets/107113353/333de889-fdf7-4bec-bb05-70b24fda9151)

**Comment by rohitmondal03** [comment]
> Hi, @rohitmondal03, thanks for reporting this issue!

@NathanTarbert Can I work on it ??

**Comment by NathanTarbert** [comment]
@rohitmondal03, done!

**Comment by rohitmondal03** [comment]
@NathanTarbert I'm pushing the issue in `main` branch but after commiting their is a message showing `→ No staged files match any configured task.` Can you help me with this ?
