### ISSUE TITLE
Add Contrib.rocks to README

### ISSUE THREAD

**Issue by NathanTarbert** [boxyhq/saas-starter-kit#625]
### Guidelines 👇🏼
If you would like to be rewarded by BoxyHQ for your participation in contributing to Hacktoberfest, [please register for our Hacktoberfest event](https://events.mlh.io/events/10461-boxyhq-hacktoberfest-2023).

___

Add contrib.rocks to the SaaS Starter Kit README below the Community section and above the License section so we can showcase our appreciation for our open-source contributors.

![image](https://github.com/boxyhq/saas-starter-kit/assets/66887028/60e7fea8-3b0b-42a3-9484-1bafa6b2823c)

**Comment by ArturBa** [comment]
let me take care of it

**Comment by NathanTarbert** [comment]
Sure, just submit a PR
