### ISSUE TITLE
UI issue in pricing and feature section in dark mode

### ISSUE THREAD

**Issue by rohitmondal03** [boxyhq/saas-starter-kit#636]
In dark mode the pricing section's border are not clearly visible
![Screenshot (100)](https://github.com/boxyhq/saas-starter-kit/assets/107113353/e2db4a5b-ca56-4219-b8b7-3c77ec6dff2b)

Also it'll be nice if we add some border to each features in feature section.
![Screenshot (99)](https://github.com/boxyhq/saas-starter-kit/assets/107113353/c29c60f9-23f3-4455-bcd7-b444ad4bc60a)

**Comment by devkiran** [comment]
@rohitmondal03 Thanks for reporting. Feel free to open a PR.

**Comment by rohitmondal03** [comment]
@devkiran you assigned the issue to me !!
