### ISSUE TITLE
Suggestion to Enhance User-Friendliness through Social Media Handle Logos

### ISSUE THREAD

**Issue by moheyt** [boxyhq/saas-starter-kit#638]
Currently, you're using text-based links for your social media handles on your website, emails, and other digital communication channels. While this practice effectively conveys the information, it might not be the most user-friendly approach. Users often process visual information more quickly and accurately than text, and the use of logos or icons alongside your social media links can significantly improve user engagement and recognition.

Integrating logos or icons representing each of your social media platforms alongside the corresponding links. This would not only make it easier for users to identify and connect with us on their preferred social media channels but also contribute to a more cohesive and visually appealing brand image.
![Screenshot 2023-10-15 000219](https://github.com/boxyhq/saas-starter-kit/assets/85775976/9bcc67d5-13b4-4c4a-8d1b-1fa44a9d87b8)

I would like to fix this. Please assign me. #Hacktoberfest

**Comment by NathanTarbert** [comment]
@moheyt, this Issue would be more fitting on our website. Can you please post it there and I can assign you and we would be happy to review your PR?
https://github.com/boxyhq/website

**Comment by moheyt** [comment]
sure @NathanTarbert also please assign it under hackoctoberfest tag.

**Comment by devkiran** [comment]
Closing this. I see a new issue created here https://github.com/boxyhq/website/issues/294

**Comment by devkiran** [comment]
Closing this. I see a new issue created here https://github.com/boxyhq/website/issues/294

**Comment by moheyt** [comment]
hey @devkiran but you close it in both issues.

**Comment by devkiran** [comment]
@moheyt https://github.com/boxyhq/website/issues/294

**Comment by moheyt** [comment]
My bad @devkiran 
Can you please assign this issue to me?
