### ISSUE TITLE
JoinWithInvitation flow is broken when confirmEmail is true

### ISSUE THREAD

**Issue by ashutoshdas96** [boxyhq/saas-starter-kit#653]
The confirmation email lacks the `inviteToken`. 

I solved it in my app by passing the inviteToken to `/api/auth/join` POST request and added a new query-string, `inviteToken` in `sendVerificationMail`.

Finally in `/auth/verify-email-token`, I have added the `token` query to `/auth/login?success` redirect.

The whole flow seems very complicated and can be simplified a lot.

**Comment by devkiran** [comment]
Thanks for the feedback. I agree that the flow is a bit complicated. We'll look into simplifying it. Let me know if you have any suggestions.

**Comment by devkiran** [comment]
The invitation flow has been improved in this PR #672. Closing this issue. Feel free to open a new issue if you have any other feedback.
