### ISSUE TITLE
Internationalization (i18n): Add remaining translation strings

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#67]
- Add the remaining translation string to `locales/en`
- Use the translation keys in the components and pages.

Example

https://github.com/boxyhq/saas-starter-kit/blob/5892c500b2860a10a3e73b4f9d89d74870e2748f/locales/en/common.json#L1-L4

https://github.com/boxyhq/saas-starter-kit/blob/3a98928996a5b05581d5a9d90931d1223765e475/pages/dashboard.tsx#L9

https://github.com/boxyhq/saas-starter-kit/blob/3a98928996a5b05581d5a9d90931d1223765e475/pages/dashboard.tsx#L16

**Comment by deepakprabhakara** [comment]
@gitstart-boxyhq Please taken a look
