### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by devkiran** [boxyhq/saas-starter-kit#7]
As a user I should be able to login with social login such as Github, Google.

NextAuth.js support social login.

- Add social login button to the login and signup page.
- Update the README with the appropriate instructions.

**Comment by meenaljain0303** [comment]
I would like to contribute to this issue.

**Comment by devkiran** [comment]
@meenaljain0303 Please pick one issue to get started. If you have any questions, message us on the Discord channel.

**Comment by Saptarshee94** [comment]
How about these? Buttons added but struggling with the integration.
### Login Page:
![image](https://user-images.githubusercontent.com/45600689/194537628-1bbb43c9-bb3f-45e9-88d4-eaaff108179d.png)
### Sign Up Page:
![image](https://user-images.githubusercontent.com/45600689/194537811-095ab7f6-9a8a-4da3-8d55-350abbe33692.png)

**Comment by devkiran** [comment]
Looks good to me. Great work. We use NextAuth to implement the authentication. I think it is straightforward to add the social login via NextAuth. Please review the Documentation. Let us know if you have any specific questions.

**Comment by Saptarshee94** [comment]
Issue addressed in PR #38
Due to some local issue I could not test what happens after successfully signing in through social login.
Need to test that scenario.
