### ISSUE TITLE
New Team action in the Sidebar doesn't open the Modal when it was open once

### ISSUE THREAD

**Issue by vrmartins** [boxyhq/saas-starter-kit#739]
This bug can be reproducible following the steps below:
* Login
* On the sidebar, click on "New Team"
    * It will open the modal
* Close the modal
* On the sidebar, click again on "New Team"
    * It will do nothing

**Comment by yacineahmaich** [comment]
Hi, can you assign me this issue?
I already figured out the source of the problem and I can fix it immediately.
