### ISSUE TITLE
Apache 2.0 License?

### ISSUE THREAD

**Issue by layinka** [boxyhq/saas-starter-kit#863]
Hi All,
Great work on this starter, but i think the Apache 2.0 license is rather too restrictive for a starter, as it requires every derivative work to also carry the same license.
As its a starter, what if i want to choose not to open source my code?

**Comment by deepakprabhakara** [comment]
@layinka That is not the correct interpretation of Apache 2.0 license, it is an extremely permissive license and you do not have to open source your code based on the SaaS starter kit.

```
No Compulsion for Derivative Works to be Open-Sourced
This means that if you create a derivative work based on an Apache-licensed project, you are under no obligation to release it under the same or similar open-source license.
```

Please check https://memgraph.com/blog/apache-license-2-0 for more details.

**Comment by schalkneethling** [comment]
> Hi All, Great work on this starter, but i think the Apache 2.0 license is rather too restrictive for a starter, as it requires every derivative work to also carry the same license. As its a starter, what if i want to choose not to open source my code?

Hey @layinka - Echoing what @deepakprabhakara said. You are under no obligation to open source the code you write on top of the SaaS starter kit. Does this answer your question? Thanks so much for your interest in this project. Should you build something using the starter kit, we would love to know more! Good luck.
